# Generated by Django 5.2.17 on 2026-10-01 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Judul resep')),
                ('ingredients', models.TextField(help_text='Satu bahan beserta takaran per baris.', verbose_name='Bahan dan takaran')),
                ('steps', models.TextField(help_text='Satu langkah per baris.', verbose_name='Langkah memasak')),
                ('portions', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porsi')),
                ('minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Waktu memasak (menit)')),
                ('image_url', models.URLField(blank=True, verbose_name='URL foto (opsional)')),
                ('demo_image', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('portions__gte', 1)), name='recipe_portions_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('minutes__gte', 1)), name='recipe_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_bookmark'),
        ),
    ]
