# Generated by Django 5.2.17 on 2026-10-01 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama bahan makanan')),
                ('category', models.CharField(choices=[('Buah Segar', 'Buah Segar'), ('Sayuran', 'Sayuran'), ('Susu', 'Susu'), ('Yogurt', 'Yogurt'), ('Protein', 'Protein'), ('Bahan Pokok', 'Bahan Pokok'), ('Lainnya', 'Lainnya')], max_length=30, verbose_name='Jenis makanan')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah stok')),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('gram', 'gram'), ('liter', 'liter'), ('pack', 'pack'), ('botol', 'botol'), ('kotak', 'kotak')], default='pcs', max_length=12, verbose_name='Satuan')),
                ('location', models.CharField(choices=[('Kulkas', 'Kulkas'), ('Freezer', 'Freezer'), ('Rak Dapur', 'Rak Dapur')], max_length=30, verbose_name='Lokasi penyimpanan')),
                ('expires_on', models.DateField(verbose_name='Tanggal kedaluwarsa')),
                ('stored_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal masuk penyimpanan')),
                ('image_url', models.URLField(blank=True, verbose_name='URL foto (opsional)')),
                ('barcode', models.CharField(blank=True, max_length=32)),
                ('is_demo', models.BooleanField(default=False, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_on', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='pantry_quantity_positive')],
            },
        ),
    ]
